const SEARCH_INDEX = [
  {
    "title": "Building an Intelligent Video Analyst: Crafting the Agent's Brain (Part 2)",
    "slug": "building-an-intelligent-video-analyst-crafting-the-agents-brain-part-2",
    "date": "2025-09-22",
    "summary": "A robust pipeline is just the beginning; the real intelligence comes from the agent's 'brain.' This post is a deep dive into the art of prompt engineering, showing how carefully crafted instructions enable our `Agno` agent to not only analyze video with Google Gemini but also to autonomously use web search tools for a richer, more contextual analysis. See how the final pieces came together to create an intelligent video research assistant.",
    "tags": [
      "Python",
      "Streamlit",
      "Agno",
      "Google Gemini",
      "DuckDuckGo API",
      "google-generativeai",
      "python-dotenv",
      "Agentic AI",
      "Multimodal AI",
      "Generative AI",
      "LLM",
      "Video Analysis",
      "AI Agent",
      "Prompt Engineering",
      "Asynchronous API",
      "Data Pipeline",
      "Natural Language Processing"
    ]
  },
  {
    "title": "Building an Intelligent Video Analyst: The Foundational Pipeline (Part 1)",
    "slug": "building-an-intelligent-video-analyst-the-foundational-pipeline-part-1",
    "date": "2025-09-21",
    "summary": "My journey to build an intelligent video analyst started with what seemed like a simple task: uploading a video. I quickly hit a wall with Google's asynchronous File API, a common real-world challenge that requires more than just basic code. This post covers the architectural decisions, the code for building a resilient video processing pipeline, and the \"aha!\" moment that made it all work, setting the stage for the AI agent.",
    "tags": [
      "Python",
      "Streamlit",
      "Agno",
      "Google Gemini",
      "DuckDuckGo API",
      "google-generativeai",
      "python-dotenv",
      "Agentic AI",
      "Multimodal AI",
      "Generative AI",
      "LLM",
      "Video Analysis",
      "AI Agent",
      "Prompt Engineering",
      "Asynchronous API",
      "Data Pipeline",
      "Natural Language Processing"
    ]
  },
  {
    "title": "Multi-Agent Chaos: When AI Agents Wouldn't Cooperate",
    "slug": "multi-agent-chaos-when-ai-agents-wouldnt-cooperate",
    "date": "2025-09-20",
    "summary": "My journey to build an AI financial analyst started with a single, confused bot that failed miserably. The solution wasn't a better model, but a better architecture: a coordinated team of AI specialists. Here's a deep dive into the code, the struggles, and the key lessons learned from building a multi-agent system with Agno and Groq.",
    "tags": [
      "Python",
      "Agno",
      "Groq",
      "Agentic AI",
      "Multi-Agent Systems",
      "FastAPI",
      "DuckDuckGoTools",
      "YFinanceTools",
      "Google API",
      "Multi-Agent AI System",
      "Financial Analysis",
      "Stock Market",
      "Investment Research",
      "Agent Coordination Patterns",
      "YFinance API",
      "Automation"
    ]
  },
  {
    "title": "Student Performance Prediction: When Simple Isn't Always Better",
    "slug": "student-performance-prediction-when-simple-isnt-always-better",
    "date": "2025-09-19",
    "summary": "A candid, in-depth account of developing an end-to-end Student Performance Prediction system. This post explores the journey from an experimental Jupyter Notebook to a production-ready, modular ML pipeline, covering the critical roles of custom logging, exception handling, and a component-based architecture. It also details the real-world challenges and hard-won lessons from deploying a Flask application on AWS.",
    "tags": [
      "AWS",
      "Python",
      "Flask",
      "Scikit-learn",
      "Pandas",
      "NumPy",
      "AWS EC2",
      "AWS Elastic Beanstalk",
      "MLOps",
      "Machine Learning",
      "MLOps",
      "End-to-End ML",
      "Scikit-learn",
      "Data Pipeline",
      "ML Pipelines",
      "Model Deployment",
      "Predictive Modeling",
      "Cloud Deployment (AWS)",
      "Modular Architecture",
      "Comprehensive Loggings",
      "Production-ready Systems",
      "Data Engineering"
    ]
  },
  {
    "title": "Text Summarizer Journey: Serving the Model (Part 3)",
    "slug": "text-summarizer-journey-serving-the-model-part-3",
    "date": "2025-09-18",
    "summary": "The final step in our MLOps journey is making the trained model useful. This post covers the \"last mile\" of deployment, showing how to wrap the text summarization model in a high-performance API using FastAPI. I then walk through creating a Dockerfile to containerize the entire application, ensuring a consistent and portable service that can be deployed anywhere.",
    "tags": [
      "HuggingFace Transformers",
      "PyTorch",
      "FastAPI",
      "Docker",
      "Python",
      "Weights & Biases",
      "MLOps",
      "NLP",
      "MLOps",
      "End-to-End ML",
      "Text Summarization",
      "Deep Learning",
      "Python",
      "FastAPI",
      "Docker",
      "Containerized Deployment",
      "Experiment Tracking",
      "RESTful API"
    ]
  },
  {
    "title": "Text Summarizer Journey: The ML Engine Room (Part 2)",
    "slug": "text-summarizer-journey-the-ml-engine-room-part-2",
    "date": "2025-09-17",
    "summary": "With a robust MLOps pipeline in place, this post dives into the core machine learning workflow of the Text Summarizer project. I explore each critical stage: transforming the raw SAMSum dataset for the model, fine-tuning a pre-trained Pegasus Transformer using a configuration-driven approach, and quantitatively evaluating its performance with ROUGE metrics.",
    "tags": [
      "HuggingFace Transformers",
      "PyTorch",
      "FastAPI",
      "Docker",
      "Python",
      "Weights & Biases",
      "MLOps",
      "NLP",
      "MLOps",
      "End-to-End ML",
      "Text Summarization",
      "Deep Learning",
      "Python",
      "Machine Learning",
      "HuggingFace Transformers",
      "NLP",
      "PyTorch",
      "Pegasus Model",
      "SAMSum Dataset",
      "Modular Pipeline Architecture"
    ]
  },
  {
    "title": "Text Summarizer Journey: The MLOps Blueprint (Part 1)",
    "slug": "text-summarizer-journey-the-mlops-blueprint-part-1",
    "date": "2025-09-16",
    "summary": "My Text Summarizer project started in a Jupyter notebook\u2014a great place for experimentation, but a fragile foundation for a real application. This post details the journey of refactoring that initial script into a robust, production-ready MLOps pipeline, tackling the challenges of hardcoded paths, scattered configuration, and monolithic execution with a modular, component-based architecture.",
    "tags": [
      "HuggingFace Transformers",
      "PyTorch",
      "FastAPI",
      "Docker",
      "Python",
      "Weights & Biases",
      "MLOps",
      "NLP",
      "MLOps",
      "End-to-End ML",
      "Text Summarization",
      "Deep Learning",
      "Python",
      "Machine Learning Pipeline",
      "Software Architecture",
      "DevOps"
    ]
  },
  {
    "title": "When SageMaker Humbled Me: A Cloud-Native ML Reality Check",
    "slug": "when-sagemaker-humbled-me-a-cloud-native-ml-reality-check",
    "date": "2025-09-15",
    "summary": "I thought taking a scikit-learn model to the cloud would be simple, but AWS SageMaker taught me more about cloud architecture and DevOps than I ever expected. This post details my entire journey, from battling IAM roles and structuring S3 buckets to mastering the SageMaker training patterns that finally bridged the gap between my local machine and a production-ready endpoint. It's a story of the struggles, the breakthroughs, and the hard-won lessons learned while building a real-world ML pipeline.",
    "tags": [
      "AWS",
      "AWS SageMaker",
      "Scikit-learn",
      "AWS S3",
      "Python",
      "MLOps",
      "CloudWatch",
      "AWS",
      "Amazon SageMaker",
      "AWS S3",
      "IAM",
      "Cloud ML",
      "MLOps",
      "Machine Learning",
      "Scikit-learn",
      "Random Forest",
      "Model Deployment",
      "ML Pipeline",
      "Boto3",
      "SageMaker SDK",
      "Cloud Computing",
      "Data Science",
      "Endpoint Deployment",
      "Cloud-native Architecture",
      "Model Versioning",
      "Model Registry"
    ]
  },
  {
    "title": "From Notebook to UI: The Web Deployment Journey (Part 2)",
    "slug": "from-notebook-to-ui-the-web-deployment-journey-part-2",
    "date": "2025-09-13",
    "summary": "A machine learning model is useless if no one can use it. This post covers the \"last mile\" problem: giving my PyTorch model an interactive body. This is the story of my struggle against frozen UIs, the architectural epiphany that led to a framework-agnostic core, and the final lessons learned while building identical apps in both Flask and FastAPI.",
    "tags": [
      "PyTorch",
      "FastAPI",
      "Flask",
      "torchvision",
      "Python",
      "TensorBoard",
      "MLOps",
      "Computer Vision",
      "Transfer Learning",
      "Experiment Tracking",
      "Web Application",
      "Deep Learning",
      "Image Classification",
      "Modular Architecture"
    ]
  },
  {
    "title": "From Notebook to UI: The Local Development Journey (Part 1)",
    "slug": "from-notebook-to-ui-the-local-development-journey-part-1",
    "date": "2025-09-12",
    "summary": "My FoodVision Mini project started with a simple question in a Jupyter Notebook, but the answer required a real engineering journey. This post tells the story of how I tamed chaotic experiments with a systematic process, unlocked the true power of transfer learning through trial and error, and refactored a monolithic script into a robust, modular ML pipeline.",
    "tags": [
      "PyTorch",
      "FastAPI",
      "Flask",
      "torchvision",
      "Python",
      "TensorBoard",
      "MLOps",
      "Computer Vision",
      "Transfer Learning",
      "Experiment Tracking",
      "Web Application",
      "Deep Learning",
      "Image Classification",
      "Modular Architecture"
    ]
  },
  {
    "title": "From Messy Data to Production MLOps: My Network Security Journey (Part 2)",
    "slug": "from-messy-data-to-production-mlops-my-network-security-journey-part-2",
    "date": "2025-09-09",
    "summary": "With a working local pipeline, the \"easy\" part was next: deployment. This turned into a multi-day AWS nightmare. After successfully automating the CI/CD pipeline with GitHub Actions, the app was live but unreachable. The culprit? A single, critical line of code related to container networking. This post dives into the humbling, real-world challenges of cloud infrastructure, debugging EC2 security groups, and the final \"aha!\" moment that brought the entire system online.",
    "tags": [
      "Python",
      "MLflow",
      "Dagshub",
      "AWS EC2",
      "AWS ECR",
      "AWS S3",
      "Scikit-learn",
      "MongoDB",
      "FastAPI",
      "Docker",
      "GitHub Actions",
      "CI/CD automation",
      "Schema Validation",
      "Experiment Tracking",
      "Modular Pipeline Architecture",
      "Production-ready MLOps Pipeline",
      "Automated Threat Detection",
      "End-to-End ML Lifecycle Management",
      "Real-Time Prediction API",
      "Drift Detection Capabilities",
      "Automated Model Retraining"
    ]
  },
  {
    "title": "From Messy Data to Production MLOps: My Network Security Journey (Part 1)",
    "slug": "from-messy-data-to-production-mlops-my-network-security-journey-part-1",
    "date": "2025-09-08",
    "summary": "My journey began with a classic MLOps mistake: underestimating messy data. My model worked locally, but I spent weeks debugging failures until a breakthrough came from implementing rigorous **data validation schemas** and **drift detection**. This post covers the foundational engineering\u2014modular architecture, custom logging, and experiment tracking\u2014that's essential *before* you even think about the cloud. It\u2019s the story of building a resilient pipeline from the ground up.",
    "tags": [
      "Python",
      "MLflow",
      "Dagshub",
      "AWS EC2",
      "AWS ECR",
      "AWS S3",
      "Scikit-learn",
      "MongoDB",
      "FastAPI",
      "Docker",
      "GitHub Actions",
      "MLOps",
      "End-to-End ML Pipeline",
      "CI/CD",
      "Cloud Deployment",
      "Containerization",
      "Network Security",
      "Phishing Detection",
      "Machine Learning",
      "Data Validation",
      "Experiment Tracking",
      "Automated Deployment"
    ]
  }
];
